### ISSUE TITLE
Unable to download folder

### ISSUE THREAD

**Issue by xierongpytorch** [kynehc/clone_anonymous_github#2]
Thanks for your contribution! I can already download .py in batches, when I modified line 57 and changed -2 to -1 in download,py. But it seems that I can't download folders in batches. I don't know if I did the above correctly, thanks again!
[*] downloading files:
file request exception (retry 0): [Errno 2] No such file or directory: '../py\\VOC\\__pycache__\\__init__.cpython-37.pyc' - ../py\VOC\__pycache__\__init__.cpython-37.pyc
file request exception (retry 0): [Errno 2] No such file or directory: '../py\\VOC\\__init__.py' - ../py\VOC\__init__.py
file request exception (retry 0): [Errno 2] No such file or directory: '../py\\VOC\\__pycache__\\data_preprocessing.cpython-37.pyc' - ../py\VOC\__pycache__\data_preprocessing.cpython-37.pyc

**Comment by kynehc** [comment]
no idea why you want to modify -2 to -1 in line 57

**Comment by xierongpytorch** [comment]
> no idea why you want to modify -2 to -1 in line 57

When I run python download.py --url https://anonymous.4open.science/r/*** --dir ./py without any modification, the following error occurs: 
[*] cloning project:r
[*] downloading files:
Traceback (most recent call last):
   File "C:\Users\DELL\clone_anonymous_github-main\download.py", line 77, in <module>
     file_path = os.path.join(*file[-len(file):-2]) # * operator to unpack the arguments out of a list
TypeError: join() missing 1 required positional argument: 'path'

**Comment by kynehc** [comment]
```
$ python download.py --url https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/ --dir savepath/
[*] cloning project:840c8c57-3c32-451e-bf12-0e20be300389
[*] downloading files:
[*] files saved to:savepath/
```

it works fine on my machine, make sure you are using python3

**Comment by xierongpytorch** [comment]
> 



> ```
> $ python download.py --url https://anonymous.4open.science/r/840c8c57-3c32-451e-bf12-0e20be300389/ --dir savepath/
> [*] cloning project:840c8c57-3c32-451e-bf12-0e20be300389
> [*] downloading files:
> [*] files saved to:savepath/
> ```
> 
> it works fine on my machine, make sure you are using python3

Yes, I'm sure I'm using python3, so I changed -2 ​​to -1 and it ran successfully with the following results:
[*] cloning project:hiding_models-EAF8
[*] downloading files:
file request exception (retry 0): [Errno 2] No such file or directory: '../py\\VOC\\__pycache__\\__init__.cpython-37.pyc' - ../py\VOC\__pycache__\__init__ .cpython-37.pyc
file request exception (retry 0): [Errno 2] No such file or directory: '../py\\VOC\\__init__.py' - ../py\VOC\__init__.py
file request exception (retry 0): [Errno 2] No such file or directory: '../py\\VOC\\__pycache__\\data_preprocessing.cpython-37.pyc' - ../py\VOC\__pycache__\data_preprocessing .cpython-37.pyc

I find the save path, there is only .py in it, the folder is missing. I would be grateful if you have any comments.

**Comment by kynehc** [comment]
pls feed the url as `https://anonymous.4open.science/r/****/`, make sure there is a slash in the end.

btw, your download repo is leaked, you may want to delete it asap.

**Comment by xierongpytorch** [comment]
> pls feed the url as `https://anonymous.4open.science/r/****/`, make sure there is a slash in the end.
> 
> btw, your download repo is leaked, you may want to delete it asap.

You are right. thanks!

**Comment by macksjeremy** [comment]
Was this ever resolved? I'm also unable to download folders. 

--url
https://anonymous.4open.science/r/xxxxxxxxxxxxxxxxxxxx/
--dir
savepath/

is my args, with xxxxxx being the target repo
